//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Api.DataAccess.MemberFeedback
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditLogID { get; set; }
        public int SurrogateID { get; set; }
        public string SurrogateType { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string Modified_by { get; set; }
        public System.DateTime Modified_dt { get; set; }
    }
}
