//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Api.DataAccess.MemberFeedback
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNFG_SystemUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CNFG_SystemUser()
        {
            this.MemberFeedbacks = new HashSet<MemberFeedback>();
            this.MemberFeedbacks1 = new HashSet<MemberFeedback>();
        }
    
        public int SystemUserId { get; set; }
        public string DomainLogin { get; set; }
        public string UserName { get; set; }
        public string EmailAddress { get; set; }
        public bool boolIsActive { get; set; }
        public bool boolIsAdmin { get; set; }
        public bool boolIsAssignable { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dt { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_dt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberFeedback> MemberFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberFeedback> MemberFeedbacks1 { get; set; }
    }
}
