//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Api.DataAccess.MemberFeedback
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNFG_ReportDate
    {
        public int ReportDateID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public byte ReportDay { get; set; }
        public byte ReportMonth { get; set; }
        public string ReportMonthName { get; set; }
        public byte ReportQuarter { get; set; }
        public int ReportYear { get; set; }
        public short ReportDOW { get; set; }
        public short ReportDOY { get; set; }
        public System.DateTime MonthBeginDate { get; set; }
        public System.DateTime MonthEndDate { get; set; }
        public System.DateTime QuarterBeginDate { get; set; }
        public System.DateTime QuarterEndDate { get; set; }
        public string QuarterName { get; set; }
        public System.DateTime YearBeginDate { get; set; }
        public System.DateTime YearEndDate { get; set; }
        public bool boolIsMonthBegin { get; set; }
        public bool boolIsMonthEnd { get; set; }
        public bool boolIsClosed { get; set; }
        public string ClosedReason { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dt { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_dt { get; set; }
    }
}
