//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Api.DataAccess.MemberFeedback
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberFeedback
    {
        public int MemberFeedbackID { get; set; }
        public string MemberFeedbackCode { get; set; }
        public short CategoryID { get; set; }
        public short FeedbackTypeID { get; set; }
        public short FeedbackSourceID { get; set; }
        public short StatusID { get; set; }
        public short FunctionalID { get; set; }
        public short Branch { get; set; }
        public string AccountNumber { get; set; }
        public string MemberName { get; set; }
        public string Comment { get; set; }
        public Nullable<int> AssignedToSystemUserID { get; set; }
        public string AssignedToCopy { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public string Resolution { get; set; }
        public Nullable<int> Resolution_byID { get; set; }
        public bool boolDeleted { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dt { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_dt { get; set; }
    
        public virtual CNFG_Category CNFG_Category { get; set; }
        public virtual CNFG_FeedbackType CNFG_FeedbackType { get; set; }
        public virtual CNFG_FunctionalArea CNFG_FunctionalArea { get; set; }
        public virtual CNFG_Source CNFG_Source { get; set; }
        public virtual CNFG_Status CNFG_Status { get; set; }
        public virtual CNFG_SystemUser CNFG_SystemUser { get; set; }
        public virtual CNFG_SystemUser CNFG_SystemUser1 { get; set; }
    }
}
