//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityProviders.SqlServerProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgUserRefreshToken
    {
        public string Id { get; set; }
        public string Subject { get; set; }
        public string OrgClientId { get; set; }
        public int OrgUserId { get; set; }
        public System.DateTime IssuedUtc { get; set; }
        public System.DateTime ExpiresUtc { get; set; }
        public string ProtectedTicket { get; set; }
    
        public virtual OrgClient OrgClient { get; set; }
        public virtual OrgUser OrgUser { get; set; }
    }
}
